### ISSUE TITLE
not working on Windows!

### ISSUE THREAD

**Issue by bushmango** [Gamefroot/Gamefroot-Texture-Packer#14]
I keep getting errors with identity -- and yes ImageMagick is installed and on the path

PATH=C:\Program Files\ImageMagick-7.0.2-Q16;

Error: Command failed: identify "C:\dev\stevie\phaserGames\ToolsGfxTs\out*.png"
'identify' is not recognized as an internal or external command,
operable program or batch file.

```
at ChildProcess.exithandler (child_process.js:207:12)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:852:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at Pipe._handle.close [as _onclose] (net.js:492:12)
```

**Comment by JohannesDrexler** [comment]
You have to check "install legacy tools" when installing imagemagick. Otherwise identify.exe and many other tools will not be installed and then you get the error above.

**Comment by leegrey** [comment]
I wish I had read this earlier! I made it work by duplicating imagemagick.exe and renaming it to identify.exe and convert.exe. 
Now it works, but when I try to make a spritesheet with ```gf-pack assets/*.png``` I just get a spritesheet with the first sprite only. (Rather than the whole folder, which I assume is expected?)

**Comment by Jazcash** [comment]
Same as above, any fix?

**Comment by leegrey** [comment]
@Jazcash - FYI I never did get this to work. Good luck. I'd be interested to hear about it if you work it out.

**Comment by Furyspark** [comment]
Works if you reinstall ImageMagick with the option to install legacy tools (like JohannesDrexler said), rather than renaming executables (that's a bad habit).

Though in all honesty, this package should be updated to stop using legacy tools, if at all possible.

Though I've had an issue where it made a spritesheet for every sprite I had, which might be relevant to your issue (despite it being so old by now), which I solved by specifying a width and height (2048x2048 in my case).
